spring.data.mongodb.uri=mongodb+srv://foxyproxy:Id0BpUHgKnneKOvp@apiproxycluster.myqp3.mongodb.net/api_proxy_db?retryWrites=true&w=majority&ssl=true&sslInvalidHostNameAllowed=true
spring.data.mongodb.database=api_proxy_db
spring.data.mongodb.auto-index-creation=true
server.port=8080

app.openai.api-key=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