spring.data.mongodb.uri=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017/?authSource=prod
spring.data.mongodb.database=prod
spring.data.mongodb.auto-index-creation=true
server.port=8080

app.openai.api-key=${OPENAI_API_KEY}

# Set logging levels
logging.level.root=INFO
logging.level.nl.jimkaplan.foxy=DEBUG
spring.profiles.default=prod

# Customize Swagger UI path (optional)
springdoc.swagger-ui.path=/swagger-ui.html

# Enable or disable API docs (optional)
springdoc.api-docs.enabled=true

# Customize API docs path (optional)
springdoc.api-docs.path=/api-docs

# Add these lines to your existing application.properties
foxy.http.connect-timeout=5000
foxy.http.read-timeout=10000