spring.data.mongodb.uri=mongodb+srv://foxyproxy:Id0BpUHgKnneKOvp@apiproxycluster.myqp3.mongodb.net/api_proxy_db?retryWrites=true&w=majority&ssl=true&sslInvalidHostNameAllowed=true
spring.data.mongodb.database=api_proxy_db
spring.data.mongodb.auto-index-creation=true
server.port=8080

app.openai.api-key=[REPLACE]

# Set logging levels
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

# Optional: Set log file location
logging.file.name=application.log
